.env.example, Cargo.lock, Cargo.toml, README.md, crates/host-utils/src/fetcher.rs, crates/host-utils/src/lib.rs, justfile, validity-client/src/main.rs, zkvm-host/bin/multi.rs, zkvm-host/bin/single.rs, zkvm-host/src/lib.rs, zkvm-host/src/utils.rs
- Add statistics for multi-block execution that are always printed during execution.
- Increase the size of the KV store to support larger block ranges.
The SP1 RISC-V executor degrades after 3-4B cycles (~25 blocks), we'll need to limit the span batch to that for now for the best performance.
=> feat: add statistics tracker

Cargo.lock, Cargo.toml, crates/client-utils/Cargo.toml, crates/client-utils/src/oracle/mod.rs
- Use stable release of `kzg-rs`.
- Batch KZG verification.
=> feat: use deployed kzg-rs

proposer/succinct/bin/cost_estimator.rs
Handle the startup & shutdown logic for the span batch server inside of the cost estimator, rather than relying on user startup commands.
=> feat: add docker startup logic

contracts/zkconfig.json, proposer/op/proposer/db/db.go, proposer/op/proposer/prove.go
Small fixes to the `op-proposer` logic:
1. When an agg proof failed, we incorrectly retried a span proof with the same bounds, which caused issues. We had not run into this issue before because AGG proofs typically didn't fail. The Modal proof server was not up, which is why the AGG proofs failed.
2. In the start of the `ProcessPendingProofs` loop, we should only retry failed proofs IF they did not reach the prover network. Otherwise, we will constantly retry failed proofs from the prover network, which causes issues.
=> fix: `op-proposer` logic

proposer/succinct/bin/cost_estimator.rs, proposer/succinct/build.rs
Clear the data directory before each witness generation run in the event there is a failure on a previous witness generation run. 
Mirrors the logic within the multi and single block executors, as well as the `op-succinct` proving server.
=> chore: Reset witnessgen data directory

proposer/succinct/bin/cost_estimator.rs, proposer/succinct/bin/server.rs, scripts/prove/bin/multi.rs, scripts/prove/bin/single.rs, utils/host/src/fetcher.rs, utils/host/src/witnessgen.rs
Centralize logic for adding/deleting witness generation files into `get_host_cli_args`.
Reduce witness generation timeout to 1 minute, as most `witnessgen` takes less than that.
=> chore: `CacheMode`

contracts/zkconfig.json, proposer/op/proposer/db/db.go, proposer/op/proposer/driver.go, proposer/op/proposer/flags/flags.go, proposer/op/proposer/prove.go, proposer/op/proposer/service.go
Add a flag to use the cached DB at the `dbPath` in the proposer. Removes the need to delete the DB manually.
This flag can be activated with `USE_CACHED_DB`.
=> feat: Add `useCachedDB` flag

scripts/prove/bin/cost_estimator.rs
Fix how the `cost-estimator` splits the span batch ranges `span-batch-server` according to the configuration per chain. There should be no overlap between ranges, otherwise there will be double execution of the same block.
=> fix: cost estimator

programs/range/src/main.rs, proposer/op/Dockerfile.op_proposer, proposer/op/Dockerfile.span_batch_server, proposer/op/cmd/main.go, proposer/op/proposer/span_batches.go, proposer/op/proposer/utils/utils.go, proposer/op/server/main_test.go, scripts/prove/bin/cost_estimator.rs, utils/host/src/rollup_config.rs, utils/host/src/witnessgen.rs
Load the OP Stack rollup config in the batch decoder. If the span batch decoding fails, just return a single range.
- Add cycle tracking for repeated block derivation. Occurs when processing multiple span batches in the same proof.
- Parse the Rust rollup config from Go.
- Pass in the verbosity flag to the `native-host-runner`.
=> feat: Load OP Stack Rollup Config

docker-compose.yml, proposer/op/op_proposer.sh, proposer/op/proposer/config.go, proposer/op/proposer/flags/flags.go
Configure the DB path to be indexed by chain ID so multiple proposers can be run on the same machine.
Changes `dbPathFlag` to point to a directory rather than a file.
=> feat: db path indexed by chain id

book/architecture.md, book/getting-started/intro.md, book/introduction.md
=> docs: fix typos

Cargo.lock, Cargo.toml, book/getting-started/prerequisites.md, utils/host/Cargo.toml, utils/host/src/fetcher.rs
If the `optimism_safeHeadAtL1Block` method is available, use it to fetch the `l1Head`. If it's not available, or it can't be used to find the `l1Head`, default to the max delay from which a batcher can post.
=> feat: Use `optimism_safeHeadAtL1Block` if available

book/SUMMARY.md, book/advanced/intro.md, scripts/utils/bin/vkey.rs
Add instructions for verifying the program binaries.
=> feat: verifiable binaries

.gitignore, Cargo.lock, utils/host/Cargo.toml, utils/host/src/witnessgen.rs
Include the end block when a witness generation process fails.
=> chore: error messages

proposer/op/proposer/db/db.go, proposer/op/proposer/driver.go, proposer/op/proposer/prove.go
Add relevant metrics to the proposer that are logged in each iteration.
These metrics can be dumped to instrumentation/monitoring in the future.
=> feat(proposer): metrics

proposer/op/proposer/db/db.go, proposer/op/proposer/prove.go
In SQLite, there can only be one write operation at a time.
Previously, this caused `database is locked` errors, which did not cause downtime on the application, but are good to handle more correctly.
Create a `writeClient` that uses `setMaxOpenConnections` to provide a Mutex for write queries, and a `readClient` with several open connections.
Optimizations from: https://kerkour.com/sqlite-for-servers, used https://entgo.io/docs/sql-integration/ for the `ent` integration.
=> feat(proposer): SQLite changes

Cargo.lock, Cargo.toml, proposer/op/proposer/db/db.go, proposer/op/proposer/db/ent/schema/proofrequest.go, proposer/op/proposer/driver.go, proposer/op/proposer/prove.go
- Implement the changes recommended in the TL;DR section of https://kerkour.com/sqlite-for-servers
- Downgrade to `rc3` for experimental cluster testing.
- On restart, correctly mark the witness generation proofs as failed. Previously, it set the proofs in `PROVING` state to failed.
- Add a maximum limit for the number of concurrent witness generation requests by a single proposer. Otherwise, due to the lack of safety in Kona I/O, witness generation processes can unexpectedly die. https://github.com/anton-rs/kona/issues/553
=> fix(proposer): SQLite fixes

book/getting-started/configuration.md
Resolves https://github.com/succinctlabs/op-succinct/issues/157
=> docs: `finalizationPeriod`

Cargo.lock, Cargo.toml, book/getting-started/configuration.md, configs/13269/rollup.json, configs/15107/rollup.json, justfile, proposer/op/proposer/driver.go, proposer/op/proposer/prove.go, proposer/op/proposer/rpc_types.go, proposer/succinct/Cargo.toml, proposer/succinct/bin/server.rs, proposer/succinct/src/lib.rs, scripts/prove/bin/multi.rs, scripts/prove/build.rs, scripts/utils/Cargo.toml, scripts/utils/bin/update_vkeys.rs, scripts/utils/bin/vkey.rs, utils/host/Cargo.toml, utils/host/src/fetcher.rs, utils/host/src/lib.rs
The updated version of `kona` from https://github.com/succinctlabs/op-succinct/pull/174 doubled the derivation cycle counts. In a future PR, I'll add performance regression testing which will verify that changes pulled in from `kona` aren't dramatically alerting the proving cost.
For now, use this branch of kona (https://github.com/moongate-forks/kona/pull/28), which uses a version of `kona` from a few weeks ago in addition to the bug fixes for https://github.com/anton-rs/kona/pull/573 and https://github.com/anton-rs/kona/pull/705
This PR also cherry-picks the changes from #175 , #176, #177
=> feat: downgrade `kona`

.gitignore, Cargo.lock, Cargo.toml, configs/60808/rollup.json, configs/70028/rollup.json, programs/range/Cargo.toml, programs/range/src/main.rs, scripts/fees/src/lib.rs, scripts/prove/Cargo.toml, scripts/prove/bin/agg.rs, scripts/prove/bin/multi.rs, scripts/utils/Cargo.toml, scripts/utils/bin/cost_estimator.rs, utils/build/src/lib.rs, utils/host/src/fetcher.rs, utils/host/src/stats.rs, utils/host/src/witnessgen.rs
- Add `total_tx_fees` to the `BlockInfo`. Useful for determining the total fees collected by the rollup.
- Simplify the `cost_estimator`. Write to the CSV progressively.
- Add `client` logs by adding a `tracing_subscriber` feature, mimicking the `kona-client`.
=> feat: simplify cost estimator

utils/host/src/fetcher.rs
Add methods to fetch the `L2BlockInfo`. Simplify the error message returned by the `fetcher` if an RPC method doesn't exist.
=> feat(fetcher): `l2BlockInfo` methods

Cargo.lock, utils/host/Cargo.toml, utils/host/src/witnessgen.rs
Kill the spawned native programs using the `sysinfo` crate, by killing all of the processes that have a `native_host_runner` parent process in the witness generation list.
The previous methodology of killing all native programs with a specified name (e.g. `range`) on the machine caused issues, because a single failed witness generation process would inadvertently kill all other ongoing witness generation processes. This made it difficult to discover which witness generation process had an issue.
Reorganize the `Cargo.toml` inside of `op-succinct-host-utils` to be more straightforward.
=> refactor(witnessgen): error handling

README.md
Add a warning for `main`'s status as a development branch.
=> docs: branch warning

scripts/prove/bin/multi.rs, scripts/prove/bin/single.rs, scripts/utils/bin/cost_estimator.rs, utils/host/src/fetcher.rs, utils/host/src/stats.rs
The state of the `ExecutionReport` is difficult to reason about because it's progressively updated with new data. Refactor the `ExecutionReport` to be initialized once to simplify the state pattern.
=> refactor: simplify cost estimator

Cargo.lock, configs/480/rollup.json, proposer/db-utils/query_proofs.py, proposer/op/proposer/driver.go, proposer/op/proposer/metrics/metrics.go, proposer/op/proposer/metrics/noop.go, proposer/op/proposer/prove.go, proposer/op/proposer/rpc_types.go, proposer/op/proposer/span_batches.go, proposer/succinct/Cargo.toml, proposer/succinct/bin/server.rs, proposer/succinct/src/lib.rs
- Add error handling based on the `UnclaimDescription`. If a proof failed due to `program execution error`, split the proof in half.
- Add argument for `query_proofs.py`.
- Add metrics for errors + prove failures + witness gen failures.
- Backoff on `validateConfig` to avoid throwing unnecessary errors.
- Use `int`'s instead of strings for better type handling in the RPC.
=> feat(proposer): Error handling

Cargo.lock, proposer/succinct/bin/server.rs, scripts/prove/bin/multi.rs, scripts/prove/bin/single.rs, scripts/utils/Cargo.toml, scripts/utils/bin/block_data.rs, scripts/utils/bin/cost_estimator.rs, scripts/utils/bin/fetch_rollup_config.rs, utils/host/src/fetcher.rs, utils/host/src/rollup_config.rs
- Create a `DataFetcher::new_with_rollup_config` method that loads and saves the rollup config. This enables initializing the data fetcher without a valid `L2_NODE_RPC` (or one with the specified endpoints for `op-succinct` enabled), which is useful for fetching the L2 block/fee data.
- Incrementally write the block data in the `block-data` script, so at least a partial amount of the data will be written.
=> feat: data fetcher fixes

scripts/prove/bin/agg.rs, scripts/utils/bin/cost_estimator.rs
Load the rollup config in the data fetcher for the `agg` and `cost_estimator` scripts.
=> fix(scripts): Load rollup config

Cargo.lock, scripts/prove/bin/multi.rs, scripts/utils/bin/cost_estimator.rs, utils/host/Cargo.toml, utils/host/src/block_range.rs, utils/host/src/lib.rs
Add a check that the blocks supplied for the cost estimator or the multi script are finalized to ensure that the batch data has been posted to the L1.
Addresses GRO-293
=> feat(scripts): Add finalized block check 

.github/workflows/integration-tests.yml, scripts/prove/Cargo.toml, scripts/prove/bin/multi.rs, scripts/prove/src/lib.rs, scripts/prove/tests/common/mod.rs, scripts/prove/tests/multi.rs, scripts/utils/bin/cost_estimator.rs, utils/host/src/block_range.rs, utils/host/src/fetcher.rs, utils/host/src/stats.rs
The goal of this PR is to display stats on a proof execution on CI.
In order to not pollute `multi` binary with CI related stuff, I did a small refactoring of the witness generation and proof execution part, moving them to `lib` so they can be used by the binary and also an integration test.
The code that call Github API is mainly copied from the one in SP1.
I also did a small change to the cost estimator binary to alway take a block range in the last 2 weeks.
=> feat: display cycle count on CI

Cargo.lock, proposer/op/op_proposer.sh
Add a default block range of 300. This configuration works well for empty chains.
=> feat: Add default block range

.github/workflows/integration-tests.yml, scripts/prove/tests/multi.rs
Adds an `POST_TO_GITHUB` env variable to control when report is posted to GitHub.
=> fix: post report to GitHub on PRs only

scripts/prove/src/lib.rs, scripts/prove/tests/multi.rs
Use `get_rolling_block_range()` on the multi test.
=> fix: generate the report on fixed blocks

utils/host/src/fetcher.rs
If the user does not supply one of the RPC's or the URL is invalid, return an error.
=> fix: Error for invalid URL

book/getting-started/configuration.md, book/getting-started/l2-output-oracle.md, contracts/opsuccinctl2ooconfig.json, contracts/script/OPSuccinctDeployer.s.sol, contracts/script/OPSuccinctUpgrader.s.sol, contracts/test/helpers/Utils.sol, justfile, scripts/utils/bin/cost_estimator.rs
Separate fetching the rollup config + deploying the contract, rather than using a forge FFI script.
`just deploy-oracle` and `just upgrade-oracle`
=> refactor: contract deployment

book/advanced/l2-output-oracle.md, contracts/opsuccinctl2ooconfig.json, contracts/src/OPSuccinctL2OutputOracle.sol, contracts/test/Upgrade.t.sol, contracts/test/helpers/JSONDecoder.sol, contracts/test/helpers/Utils.sol, scripts/utils/bin/fetch_rollup_config.rs
- Add back the `owner` parameter, which will simplify upgrades and make management of the contract straightforward. Rather than needing to re-initialize the contract, just use the `onlyOwner` modifier to update the verification key. The `owner` can be the governance smart contract or a multi-sig. Effectively reverts https://github.com/succinctlabs/op-succinct/pull/184
- Modify `verifierGateway` -> `verifier` and use `ISP1Verifier`, rather than `ISP1VerifierGateway`, as the `verifierGateway` terminology is confusing and unnecessary for this context.
- Add all initialization parameters to `initParams`.
=> feat(contracts): Add modifiers, owner

.github/workflows/test.yml, book/advanced/l2-output-oracle.md, contracts/src/OPSuccinctL2OutputOracle.sol
Support multiple proposers on the contract.
If `address(0)` is whitelisted, then permissionless proposing is enabled.
Otherwise, the account proposing a new output root with a proof must be explicitly enabled.
=> feat(contracts): Support multiple proposers

Cargo.lock, Cargo.toml, contracts/opsuccinctl2ooconfig.json, justfile
The executor optimizations included a change which made the vkey setup inconsistent. Use a new branch for consistency.
=> chore: misc fixes

proposer/op/proposer/flags/flags.go, proposer/op/proposer/prove.go
The proof timeout logic was necessary when we could not assume that the network would correctly set the status of the proof to failed, and the application (op-succinct) had to do this itself to re-request a proof.
This inadvertently causes a backlogged cluster to become even more backlogged. 
Ex.
Requested proofs on the cluster (which are capped at `maxConcurrentProofRequests` per proposer) have been generating for > `proofTimeout` seconds (e.g. 4 hours). The application "times out" the proofs in it's own state, and re-requests the proofs, putting more load on the network.
=> feat(proposer): remove manual network proof timeout

Cargo.lock, proposer/op/proposer/service.go, proposer/op/proposer/span_batches.go, proposer/op/proposer/span_batches_test.go, scripts/utils/Cargo.toml, scripts/utils/bin/cost_estimator.rs, utils/host/src/fetcher.rs
To reduce derivation overhead, we can split the ranges based on the batches posted to L1 if the `safeDb` is enable on the rollup `op-node` RPC.
We can make use of `optimism_safeHeadAtL1Block` for doing this if it exists on the node.
Add these changes in both the `cost-estimator` and `proposer`.
=> feat(cost-estimator+proposer): split range based on `optimism_safeHeadAtL1Block`

Cargo.lock, Cargo.toml
Update `kona-host` to use `kzg-rs` feature, rather than `c-kzg`.
Decreases blob verification cycle counts by 10x.
=> feat: Use `kzg-rs`, rather than `c-kzg`

Cargo.lock, Cargo.toml, utils/client/src/oracle/mod.rs
Bump branch of `kona` to use `k256` feature from `revm`.
We could also enable this with the `secp256k1` patch.
=> feat(range): use `k256` feature in `revm`

contracts/src/OPSuccinctL2OutputOracle.sol
To keep track of the "upgrade" version of the contract, and not the semantic version, add `initializerVersion` constant.
=> feat(contracts): add initializer version

proposer/succinct/bin/server.rs, scripts/utils/bin/fetch_rollup_config.rs
Use `RunContext::Docker` inside of the `WitnessGenExecutor` for mock mode.
=> fix: clippy, run context

proposer/op/proposer/range.go
It is possible for the `safeDB` to exist, but `optimism_safeHeadAtL1Block` fails on a specific block because the `safeDb` is not fully synced.
In this case, add a fallback to the safe db range-splitting algorithm to use the basic range splitting algorithm in the event of an error.
=> fix(proposer): `SplitRangeBasedOnSafeHeads` fallback

book/advanced/proposer.md, proposer/succinct/bin/server.rs
Add more informative logging in the OP Succinct server.
Difficult to parse `anyhow` errors inside of the OP Succinct proposer, better to explicitly log error messages upon failure.
=> feat: proposer server error handling + docs

proposer/op/proposer/prove.go, proposer/op/proposer/range.go
Split the range according to `splitRangeBasic`, as advanced range splitting is an over-optimization.
Don't split the range on failure in half until we have more insight into the error type. We should only split on execution errors for the span proofs.
=> fix(proposer): submission interval

proposer/succinct/build.rs, scripts/prove/build.rs, scripts/utils/build.rs, utils/build/src/lib.rs
Add `ProgramBuildArgs`, which enables declaratively specifying whether to build the native program with the `tracing-subscriber` feature on, which will emit helpful debugging logs.
=> chore: turn off native execution logging

contracts/opsuccinctl2ooconfig.json, proposer/op/proposer/prove.go, proposer/op/proposer/rpc_types.go, proposer/succinct/bin/server.rs, proposer/succinct/src/lib.rs, scripts/utils/bin/fetch_rollup_config.rs
With `network-v2`, we can use the `executionStatus` returned with a proof to split proofs based on an OOM in SP1.
Note: With the embedded allocator, this is no longer necessary.
=> feat: use execution status to split proofs

book/SUMMARY.md, book/advanced/toggle-optimistic.md, contracts/src/OPSuccinctL2OutputOracle.sol
Adds the original `proposeL2Output` function from `L2OutputOracle` in when `optimisticMode` is toggled to true.
- Adds a new optimisticMode toggle.
- When optimisticMode is false, the `proposeL2Output` function exposed is the version that accepts a proof and the checkpoint l1 block number. The only modification is that the proposer must be in the `approvedProposers` mapping.
- Removes the `forceOutputRootProposal` function.
- Adds modifier functions to enable/disable optimistic mode. Requires a finalizationPeriodSeconds to be passed in to ensure that the owner is reminded to update the finalizationPeriodSeconds when switching between op/zk modes.
- The original proposeL2Output function can be found here: https://github.com/ethereum-optimism/optimism/blob/aa81f074a84ab747ab408eb8df490a72d63 …
=> feat(contracts): optimistic mode

book/advanced/proposer.md, proposer/op/op_proposer.sh, proposer/op/proposer/config.go, proposer/op/proposer/flags/flags.go, proposer/op/proposer/prove.go, proposer/op/proposer/service.go
support configuring more or less than 5 concurrent witness gen and tunable timeout for them
=> feat(proposer): more configurability for witness gen

proposer/op/Dockerfile.op_proposer
Include sqlite3 in op proposer image to facilitate proof ops (e.g. debug local proof status, re-request failed proofs with different params)
=> chore(proposer): add sqlite3 to docker image for ops

proposer/op/proposer/prove.go
When attempting to split a block range due to unfulfillable proof: Block ranges in the DB are `[start, end)`, so start of the second half should be just `midBlock` instead of `midBlock+1`
=> fix: split midblock block number

contracts/opsuccinctl2ooconfig.json, proposer/op/proposer/prove.go, proposer/op/proposer/range.go, proposer/succinct/bin/server.rs, utils/host/src/fetcher.rs
- Reduce the number of concurrent L1 RPC requests to 10.
- Add error handling for the agg proof request.
- Handle the string error logging inside of the proposer.
=> fix: error logging

proposer/op/proposer/driver.go
If the blockhash corresponding to the block number is checkpointed, we no longer need to checkpoint the block.
=> feat(proposer): Check if blockhash is checkpointed

proposer/succinct/bin/server.rs
If `RUST_LOG` is not set before the call to:
```rust
utils::setup_logger();
```
all logging is suppressed, as [EnvFilter::try_from_default_env()
](https://github.com/succinctlabs/sp1/blob/dbe622aa4a6a33c88d76298c2a29a1d7ef7e90df/crates/core/machine/src/utils/logger.rs#L15) fails and all logging is set to `off`
=> fix: don't disable logs on the server

book/SUMMARY.md, book/troubleshooting.md
Adds a new troubleshooting.md file to the op-succinct book, providing guidance on common issues encountered and their solutions.
The doc currently handles two common issues with op-succinct; Missing Trie Node Error and L2 Block Validation Failure.
=> docs: add troubleshooting.md

utils/host/src/fetcher.rs, utils/host/src/stats.rs
Fixes fetching the block data for the very first block in the range, which is actually not executed nor proven. This prevents including non-executed blocks in stats, especially for the number of blocks, leading to more accurate estimates.
=> chore(utils): update block data range

justfile, scripts/utils/src/lib.rs, utils/host/src/block_range.rs, utils/host/src/stats.rs
Enables command to run cost estimator default, which is described in the cost estimator doc.
Includes change to use latest finalized block for end block as default. This is to avoid L2 Block Validation Failure error when
running cost estimator default.
=> fix: enable command to run cost estimator default

contracts/src/OPSuccinctDisputeGame.sol
The PR adding the `OP_SUCCINCT` game type [has been merged in optimism](https://github.com/ethereum-optimism/optimism/pull/13780#event-15982558845), but finally the number is `6`, not `3`
=> feat: update OP_SUCCINCT game type

proposer/op/proposer/db/db.go, proposer/op/proposer/prove.go
If a proof fails multiple times on the server, split it in half.
=> feat(proposer): split proofs that failed multiple times

book/fault_proofs/fault_proof_architecture.md, contracts/src/fp/OPSuccinctFaultDisputeGame.sol, contracts/src/fp/lib/Errors.sol, contracts/test/fp/OPSuccinctFaultDisputeGame.t.sol
Updates OPSuccinctFaultDisputeGame for with nits:
- Prevent front-running `prove()`/`resolve()` -> add check for `claimData.prover` to accept the initial proof
- Prevent DOS attack -> switch to pull based reward distribution like [optimism](https://github.com/ethereum-optimism/optimism/blob/d83cefb2cf3d244e29c0391e3adc56534476dc06/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L951).
=> fix: update OPSuccinctFaultDisputeGame with nits

Cargo.lock, Cargo.toml, scripts/utils/bin/fetch_rollup_config.rs
The BLS patch is unused and can be safely removed.
=> chore: remove bls patch

proposer/succinct/bin/server.rs, proposer/succinct/src/lib.rs
Previously, the memory usage in the `server` would balloon because the proving keys were cloned every time a new concurrent request was made.
We can instead wrap the `ProvingKey`, `VerificationKey` and `ProverClient` in an `Arc`, which keeps the memory usage low.
`with_state` requires that the `State` is `S: Clone + Send + Sync + 'static`.
=> chore(server): `Arc` shared state

contracts/script/OPSuccinctDGFDeployer.s.sol
Bonds are not needed for op-succinct validity DGF. This PR removes proposer bond initialization for DGF deployment.
=> feat(contracts): remove bond for validity DGF

proposer/succinct/bin/server.rs
Prevents getting below error in case where `OP_SUCCINCT_MOCK=true` but `NETWORK_PRIVATE_KEY` not set.
```
op-succinct-server-1    | NETWORK_PRIVATE_KEY environment variable is not set. Please set it to your private key or use the .private_key() method.
```
In Mock mode, we don't generate proofs through the prover network, so we should just use the `MockProver` for now. This will incur additional memory usage, and we'll optimize it in a future PR.
=> feat(server): Only use `Arc<NetworkProver>` in real proof mode

justfile
Fixes below error
```
line 196: L2OO_ADDRESS=0xA94a701A7537964D2e4Cf3fE580e2F1198180a8D: command not found
error: Recipe `update-parameters` failed with exit code 127
```
=> chore: fix just update-parameters

contracts/foundry.toml
Fixes contract verification error for `DisputeGameFactory`.
When running `just deploy-dispute-game-factory` below verification error occurred. This was due to missing change from #378, which needs `src/universal` remapping added.
```
Fail - Unable to verify. Solidity Compilation Error: Source "src/universal/interfaces/ISemver.sol" not found: File not found.
```
=> chore: fix contract verification

.github/workflows/docker-build.yaml
If the tag does not follow semver formatting (e.g. `1.0.0` or `v1.0.0`), the Docker image will not be tagged with the tag.
The following change will tag the image (e.g. `op-succinct-v1.2.0`).
=> chore(ci): docker tag

utils/host/src/rollup_config.rs
For some reason, during my test on Kurtosis Optimism package, the json returned by `debug_chainConfig` didn't contains the `terminalTotalDifficultyPassed` field.
=> fix: debug_chainConfig don't return terminalTotalDifficultyPassed

.github/workflows/test.yml, .gitmodules, contracts/foundry.toml, contracts/script/OPSuccinctDGFDeployer.s.sol, contracts/src/fp/AccessManager.sol, contracts/src/fp/OPSuccinctFaultDisputeGame.sol, contracts/src/validity/OPSuccinctDisputeGame.sol, contracts/src/validity/OPSuccinctL2OutputOracle.sol, contracts/test/fp/OPSuccinctFaultDisputeGame.t.sol, contracts/test/validity/OPSuccinctDisputeGame.t.sol, contracts/test/validity/OPSuccinctDisputeGameFactory.t.sol
Adds new features to `OPSuccinctFaultDisputeGame`
We now have game life cycle of proposed -> resolved -> finalized, where finalized is done by calling `claimCredit` after the air gap.
- "resolved" is where the game status is updated (e.g. DEFENDER_WINS), and people can do proveWithdrawals in Portal against the claim of the game
- "finalized" is where the game becomes the latest finalized anchor state, bonds are paid out and people can do finalizeWithdrawals in Portal against the claim of the game.
Previously we had a parent game type check on creation, but now it's removed for efficiency of recovery in case of game retirement.
We now allow game creation with a retired but not blacklisted, respected parent game
For improper games (either not registered, blacklisted or game type retired), …
=> feat(contracts): update `OPSuccinctFaultDisputeGame`

book/fault_proofs/challenger.md, book/fault_proofs/deploy.md, book/fault_proofs/quick_start.md, contracts/src/fp/OPSuccinctFaultDisputeGame.sol, fault_proof/Cargo.toml, fault_proof/bin/challenger.rs, fault_proof/bin/proposer.rs, fault_proof/src/config.rs, fault_proof/src/contract.rs, fault_proof/src/lib.rs
Implements challenger binary interfaces with the OPSuccinctDisputeGame implemented in #342 to challenge a game if the claim is incorrect by calling `challenge()` function in the game contract.
You can find a faulty game being challenged and resolved in favor of the challenger on ETH sepolia network: [Faulty Game Contract](https://sepolia.etherscan.io/address/0xa778317db08bb21f073af233fa5cc6358037b837), [Challenge tx](https://sepolia.etherscan.io/tx/0x5eb177a457b95a07f5f04fb92342260073c25bbd78e8e4c54f627ee256b31ed2), [Resolve tx](https://sepolia.etherscan.io/tx/0x6ab433f14c35c8cb9418636da2bae743bd6eb591f34608c9f8a634acc6c544db)
The helper functions for game resolution are now in `FactoryTrait` since game resolution is both possible for the proposer and the challenger. There is a new `enum …
=> feat: implement challenger

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, book/fault_proofs/e2e_tests.md, fault_proof/Cargo.toml, fault_proof/bin/challenger.rs, fault_proof/bin/proposer.rs, fault_proof/src/contract.rs, fault_proof/src/lib.rs, fault_proof/tests/e2e.rs
=> test: add e2e tests

justfile
This PR updates the solidity script paths within the `justfile` from `/script` to [/script/validity](https://github.com/succinctlabs/op-succinct/tree/main/contracts/script/validity)
=> fix: justfile script path

contracts/script/validity/OPSuccinctUpgrader.s.sol
If the implementation address is 0, the oracle upgrade script does not actually use the newly-deployed implementation.
=> fix: oracle upgrader can update from 0x0

justfile
Without `env`, multiple environment variables separated by spaces would cause `L2OO_ADDRESS=0x...` to attempt to be executed as a command. This would cause the entire `upgrade-oracle` command to fail.
=> fix(script): `upgrade-oracle` justfile

book/fault_proofs/challenger.md, book/fault_proofs/deploy.md, book/fault_proofs/fault_proof_architecture.md, book/fault_proofs/gas_costs.md, contracts/script/fp/DeployOPSuccinctFDG.s.sol, contracts/src/fp/OPSuccinctFaultDisputeGame.sol, contracts/src/fp/lib/Errors.sol, contracts/test/fp/OPSuccinctFaultDisputeGame.t.sol, fault_proof/bin/challenger.rs, fault_proof/bin/proposer.rs, fault_proof/src/contract.rs, fault_proof/src/lib.rs
Misc suggestions from @smartcontracts in #403 + test fixing + updating docs.
- Add the `isGameRetired` check back in because game retirement is the primary response mechanism
- Rename proof reward to challenger bond for clarity
- Add a `gameOver` function that combines the proof check + timestamp check for clarity
- General cleanup/simplification of the resolution function
=> fix: various tweaks of the succinct fdg

fault_proof/src/lib.rs
This PR modifies the `get_oldest_game_address` function to accept a parameter that determines whether to check for equality or inequality between the output root and the claim.
The `get_oldest_game_address` function is used for both defense (get_oldest_defensible_game_address) and challenging (get_oldest_challengable_game_address).
For challenging, we should challenge games where the claimed root doesn't match the actual output root (the current logic is correct for this)
For defending, we should defend games where the claimed root does match the actual output root (the current logic is incorrect for this)
So for defense, we want the opposite condition: `if output_root == game_claim`. This would mean we're defending games where the claim is correct but a challenge occurred.
=> fix(fault_proof): fix defend logic

.gitmodules, contracts/foundry.toml, contracts/src/validity/OPSuccinctDisputeGame.sol, contracts/test/validity/OPSuccinctDisputeGame.t.sol, contracts/test/validity/OPSuccinctDisputeGameFactory.t.sol
Unifies solady dependency to version v0.0.158, which is the version used by Optimism.
Necessary changes are made since LibBytes is not implemented in v0.0.158.
=> chore: unify solady

fault_proof/src/config.rs
Fixes env file for proposer from being overwritten.
Env file is already loaded in bin/proposer.rs.
```rust
async fn main() {
setup_logging();
let args = Args::parse();
dotenv::from_filename(args.env_file).ok();
```
=> fix(fault_proof): fix env file from being overwritten

contracts/src/fp/OPSuccinctFaultDisputeGame.sol, contracts/src/fp/lib/Errors.sol, contracts/test/fp/OPSuccinctFaultDisputeGame.t.sol
Made misc changes to `OPSuccinctFaultDisputeGame`.
1. Removed redundant game resolution check in `closeGame` since the subsequent call to `ANCHOR_STATE_REGISTRY.isGameFinalized(IDisputeGame(address(this)))` verifies the game's resolution status.
2. Refactored to use = instead of += for bond distribution.
3. Added proposal status sanity check for resolution.
4. Added credit getter like OP's implementation.
5. Added dispute game factory check since there could be misalignment with the factory and the game impl contract.
=> feat: make misc changes to `OPSuccinctFaultDisputeGame`

.github/workflows/ci.yaml, validity/src/utils.rs
Stats from running execute_batch `scripts/prove/tests/multi.rs` is not being reported in CI.
Updated test code, since misconfiguration disabled some unit tests, failing to catch test error. See [failed ci job](https://github.com/succinctlabs/op-succinct/actions/runs/13796640953/job/38589741396).
=> ci: filter test properly

book/fault_proofs/proposer.md, fault-proof/bin/proposer.rs, fault-proof/src/config.rs, fault-proof/src/contract.rs, fault-proof/src/lib.rs, fault-proof/src/proposer.rs
Adds feature to fp proposer for bond claiming from games that:
- Are finalized (resolved and airgapped)
- Has credit left to claim
Claim Credit test transaction: [tx](https://sepolia.etherscan.io/tx/0x391b21c540f96fda207abfbce54e4fa1a6cc1ccfce0ff7d478b79bb05aa3e6c1)
=> feat: add `handle_bond_claiming` for fp proposer

.github/workflows/elf.yml, Cargo.lock, fault-proof/bin/challenger.rs, fault-proof/bin/proposer.rs, fault-proof/src/proposer.rs, fault-proof/tests/integration.rs, scripts/fees/bin/l1_fee_scalar.rs, scripts/prove/bin/multi.rs, scripts/prove/tests/multi.rs, scripts/utils/bin/block_data.rs, scripts/utils/bin/config.rs, scripts/utils/bin/cost_estimator.rs, scripts/utils/bin/gen_sp1_test_artifacts.rs, scripts/utils/src/lib.rs, utils/build/src/lib.rs, utils/client/src/client.rs, utils/host/Cargo.toml, utils/host/src/fetcher.rs, utils/host/src/hosts/default.rs, utils/host/src/hosts/mod.rs, utils/host/src/lib.rs, utils/host/src/proof.rs, validity/Cargo.toml, validity/bin/validity.rs, validity/src/env.rs, validity/src/proof_requester.rs, validity/src/proposer.rs
- Create an `OPSuccinctHost` trait for Alt-DA providers to implement.
- In the host, provide separate images and binaries for Alt-DA.
- In the client, feature gate the use of the oracle pipeline.
- Remove `CacheMode`. Always delete the data directory.
- Fix deprecated clap attribute.
=> feat: Add `OPSuccinctHost` trait

book/SUMMARY.md, book/advanced/proposer.md, book/fault_proofs/best_practices.md, book/fault_proofs/proposer.md, book/fault_proofs/quick_start.md, fault-proof/src/config.rs, fault-proof/src/proposer.rs, scripts/prove/bin/multi.rs, scripts/prove/tests/multi.rs, scripts/utils/bin/cost_estimator.rs, scripts/utils/bin/gen_sp1_test_artifacts.rs, scripts/utils/src/lib.rs, utils/host/src/fetcher.rs, utils/host/src/hosts/default.rs, utils/host/src/hosts/mod.rs, validity/bin/validity.rs, validity/src/env.rs, validity/src/proof_requester.rs, validity/src/proposer.rs
Adds `no_safe_db` flag.
This flag determines whether to fallback to timestamp-based L1 head estimation even though SafeDB is not activated for op-node. When set `false`, proposer will panic if SafeDB is not available.
SafeDB is a critical component for efficient L1 head determination. When SafeDB is not enabled, the system falls back to timestamp-based L1 head estimation, which can lead to several issues:
1. Less reliable derivation
2. Potential cycle count blowup for derivation
=> feat: add `safe_db_fallback` flag

validity/src/proposer.rs
If the proof requests are made asynchronously to the prover network, timeout should be handled by checking the deadline of the proof request.
=> feat(validity): handle proof request timeout

book/fault_proofs/deploy.md, contracts/script/fp/DeployOPSuccinctFDG.s.sol
Updates contract deployment script for OP Succinct Lite.
1. Support usage of real OptimismPortal2 contract for the AnchorStateRegistry. If not provided, deploy mock OptimismPortal2 for testing.
2. Support permissioned game environment. If comma-separated list for `PROPOSER_ADDRESSES` and `CHALLENGER_ADDRESSES` are provided, only the given addresses are given permission in the AccessManager.
=> feat: update contract deployment script for fp

book/fault_proofs/challenger.md, fault-proof/bin/challenger.rs, fault-proof/src/config.rs, fault-proof/src/prometheus.rs
Now OP Succinct Lite challengers can claim bonds for the games that they have successfully challenged.
=> feat: add `handle_bond_claiming` for fp challenger

fault-proof/bin/challenger.rs, fault-proof/src/prometheus.rs, fault-proof/src/proposer.rs
Instead of total error count gauges, there's an error gauge for each actions for proposer and challenger, so that it's easier to track down the source of issue.
=> feat(fault-proof): better error gauges for fp

contracts/script/fp/UpgradeOPSuccinctFDG.s.sol, fault-proof/justfile
Now the upgrade script outputs upgrade calldata on dry run.
As mentioned in #450, most chains in production have a multi-sig or something similar and need the calldata to be outputted explicitly to upgrade.
=> feat(contracts): output upgrade calldata on dry run

book/fault_proofs/best_practices.md, book/fault_proofs/proposer.md, book/fault_proofs/quick_start.md, fault-proof/src/config.rs, fault-proof/src/proposer.rs
Adds mock mode support for OP Succinct Lite proposer.
This feature will be very useful for testing since it is much faster than generating real proofs from the Succinct Prover Network.
Test tx with fast finality mode: https://sepolia.etherscan.io/tx/0xa10cb5c1b02a2aa2824bf4bd56e022bb344fb980e3c3cdb783bded130f6d5aa5
=> feat: add mock mode support for fp proposer

Cargo.lock, Cargo.toml
Bump hana from v0.1.0-beta.8 to v0.1.0-beta.9.
There was a fix in hana for DataAvailabilityProvider impl of CelestiaDADataSource to support ETH DA fallback.
=> chore: bump hana

utils/host/src/hosts/celestia.rs
Adds branching logic to handle ETH DA fallback.
Version byte will be 0 if ETH DA batch and will be 1 if Alt DA batch.
See https://specs.optimism.io/protocol/derivation.html#batcher-transaction-format for more details.
=> feat(utils): handle eth da fallback

Cargo.lock, Cargo.toml, utils/host/src/hosts/celestia.rs
Handles EIP4844 transactions.
For batch transactions submitted with type3 transactions on Ethereum, it causes `index out of bounds` error.
Fixed to only parse the calldata and check version byte if it's a non-EIP4844 transaction.
Also a fix was made in hana: https://github.com/celestiaorg/hana/commit/6ccd085e4a52ec8ad96e77fc36c4ec496440ba44. Bumped hana from v0.1.0-beta.9 to v0.1.0-beta.10.
E2e tested. The first batcher transaction with EIP4844 transaction is https://sepolia.etherscan.io/tx/0x010b2e024a6ddd16c5b3bc9727ac80a0e772fddb801b035cb62176686175cbb0 on block [8138653](https://sepolia.etherscan.io/block/8138653)
=> feat(utils/host): handle eip4844 txs

Cargo.lock, Cargo.toml, utils/host/Cargo.toml, utils/host/src/fetcher.rs, utils/host/src/hosts/default.rs
- Add warning if chain does not enable Holocene hardfork.
- Use in-memory KV store by default. This doesn't bloat witness generation time/CPU usage significantly (as the witness is pulled in-memory to create the witness data anyways).
=> feat(proposer): remove data dir + holocene warn

Cargo.lock, utils/celestia/host/Cargo.toml, utils/celestia/host/src/blobstream_utils.rs, utils/celestia/host/src/host.rs
Fixes l1 head selection for celestia da via offchain indexer.
The offchain indexer:
- monitors L1 batch inbox transactions for Celestia references
- fetches the corresponding frame data from Celestia,
- parses frames to determine which L2 blocks they contain
- maintains an index mapping L2 block numbers to Celestia locations
- and provides an RPC API to query L2 block locations.
Using a dedicated off-chain indexer, we now,
1. Ask the Indexer: We query the indexer with the L2 block we care about.
2. Get Location: The indexer tells us the exact Celestia block height and the original L1 block where the L2 data was referenced.
3. Find Proof: We then scan forward from that L1 block to find the DataCommitmentStored event from the Blobstream contract, which is the on-chain proof that the data is …
=> fix: fix l1 head selection for celestia da

book/fault_proofs/challenger.md, fault-proof/bin/challenger.rs, fault-proof/src/config.rs
Enhances the existing challenger binary to support malicious challenging of valid games for testing defense mechanisms. 
- Added MALICIOUS_CHALLENGE_PERCENTAGE config option (0-100, default: 0)
- Enhanced challenger logic with two-priority system:
a. Challenge invalid games (honest behavior)
b. Challenge valid games at configured percentage (testing purposes)
- Added clear logging to distinguish honest vs malicious challenges
- .env.challenger.example
=> feat: implement malicious challenge

fault-proof/bin/challenger.rs, fault-proof/bin/proposer.rs, fault-proof/src/lib.rs, fault-proof/src/prometheus.rs, fault-proof/src/proposer.rs, utils/celestia/host/src/blobstream_utils.rs
- Convert sequential operations to concurrent tasks using task tracking
- Fix dashboard showing 0 values during proof generation
- Implement task spawning for game creation, defense, resolution, and bond claiming
- Add centralized task management with completion handling
- Ensure metrics collection runs independently of other operations
This prevents long-running operations (like witness generation for proof generation) from blocking metrics updates and other proposer activities.
=> fix: refactor fault-proof proposer to use task-based concurrency

utils/client/src/witness/executor.rs
=> fix: remove trace extension shortcut

Cargo.lock, book/fault_proofs/proposer.md, fault-proof/Cargo.toml, fault-proof/bin/challenger.rs, fault-proof/bin/proposer.rs, fault-proof/src/challenger.rs, fault-proof/src/lib.rs, fault-proof/src/proposer.rs
1. Improve game resolution: refac + fix proposer to resolve proven games as well.
2. Separate bond claiming based on role for clearer metrics collection.
- Update `is_claimable` to check game outcomes based on role
- Proposer: only claims from DEFENDER_WINS games
- Challenger: only claims from CHALLENGER_WINS games
=> feat: improve fault proof

Cargo.lock, Cargo.toml, fault-proof/bin/challenger.rs, fault-proof/bin/proposer.rs, utils/celestia/host/src/blobstream_utils.rs
There was an issue in the proposer for celestia da where batcher falls back to eth da for batch submission, the proposer cannot calculate safe l1 head for celestia. This was due to op-celestia indexer missing feature to handle eth da batches, only handling celestia da batches. Fix was made for op-celestia indexer in this [PR]( https://github.com/celestiaorg/optimism/pull/502), which introduces an API change.
This PR updates op-succinct's implementation according to the recent API change to calculate safe l1 head properly even the batcher posts batches to eth da on fallback.
=> feat: update to support celestia indexer changes

rust-toolchain.toml, validity/src/proposer.rs
rust nightly v1.91 breaks kona.
cycle count ci fails for this reason, but the elfs aren't changing.
=> chore: pin nightly rust toolchain

validity/Dockerfile.celestia
Align the Celestia Docker image binary name with the standard validity proposer to ensure consistent deployment across all variants. This reduces complexity of infra code switching between op-succinct and op-succinct-celestia images.
Docker image tag already differentiates the celestia variant, so having different binary name seems to just increase complexity.
=> chore: unify binary name for celestia docker image

scripts/utils/bin/fetch_fault_dispute_game_config.rs, scripts/utils/bin/fetch_l2oo_config.rs, utils/celestia/host/src/blobstream_utils.rs
Fixes to treat Blobstream endBlock as exclusive in commitment check.
Blobstream DataCommitmentStored ranges are [start, end), but the original code treated `endBlock` as inclusive.
When target_celestia_height == endBlock, we incorrectly matched the *previous* commitment and returned its L1 block,
potentially causing witness generation to later fail with "No matching event found for the given Celestia height" error.
Changed the upper-bound check to `< endBlock` and update logs to print the range as `[start, end)` for clarity.
This should fix to select the correct (later) commitment and L1 head when height hits a boundary.
=> fix: use end exclusive range

book/fault_proofs/docker.md, book/fault_proofs/proposer.md, book/fault_proofs/quick_start.md, book/validity/proposer.md
Updating docs to say that whitelisting is no longer needed and update to new prover network docs.
=> docs: update spn usage

fault-proof/src/challenger.rs, fault-proof/src/proposer.rs, fault-proof/tests/e2e.rs
Gas estimation for claimCredit txs in e2e tests started to fail recently. Fixes by explicitly setting gas limit to 200k. Empirically, claimCredit tx used gas around 130k~160k.
Some example claimCredit tx [here](https://sepolia.etherscan.io/tx/0xfcb19c20e0e356a73283395d36b2b9b944ff14b5d3dc2f47e2808e75b61d0a88).
=> test: fix e2e test

book/fault_proofs/proposer.md, fault-proof/src/config.rs, fault-proof/src/lib.rs, fault-proof/src/proposer.rs, fault-proof/tests/common/process.rs
Get all defensible game addresses and spawn a task for all of them, instead of doing it for the oldest only.
=> feat: spawn defense tasks concurrently

book/fault_proofs/proposer.md, fault-proof/src/config.rs, fault-proof/src/proposer.rs, fault-proof/tests/common/process.rs
Adding `RANGE_PROOF_STRATEGY` and `AGG_PROOF_STRATEGY` to fault-proof proposer so that proof fulfillment strategies are configurable. No longer defaults to `FulfillmentStrategy::Hosted`.
=> feat: add env-configurable proof fulfillment strategies

Cargo.lock, Cargo.toml
Bumps op-succinct to v3.2.0 for a new release.
=> chore: bump to v3.2.0

validity/src/proposer.rs, validity/src/types.rs
Get the execution stats from the network using `get_proof_request()`
=> feat: get execution stats from network when not in mock mode
