succinctlabs/op-succinct

- Cargo.lock
- Cargo.toml
- crates/client-utils/Cargo.toml
- Update `sp1` to `experimental`.
- Bump `kona` version.
> chore: update crate versions

- .gitignore
- Cargo.lock
- Cargo.toml
- crates/client-utils/src/precompiles/mod.rs
- crates/host-utils/src/fetcher.rs
- zkvm-host/bin/agg.rs
- zkvm-host/bin/fetch_and_save_proof.rs
- zkvm-host/bin/multi.rs
- zkvm-host/build.rs
- zkvm-host/src/lib.rs
- zkvm-host/src/stats.rs
- Fix block past L1 head.
- Use BN patch and add cycle tracking for the total cycles used by BN.
- Write the output of both native gen and proof gen to a directory prefixed with the chain id.
> feat: Use `bn` patch to test on blocks with `bn`

- CYCLE_COUNT.md
- Cargo.lock
- Cargo.toml
- README.md
- crates/client-utils/Cargo.toml
- crates/client-utils/src/driver.rs
- validity-client/Cargo.toml
- validity-client/src/main.rs
- zkvm-host/Cargo.toml
Add documentation on how to fetch cycle counts.
> docs: Add cycle count program

- .github/workflows/compile.yaml
- .github/workflows/op_proposer.yaml
- .github/workflows/pr_lint.yml
- .github/workflows/test.yml
- contracts/zkconfig.json
- op-proposer-go/proposer/driver.go
- op-proposer-go/proposer/proposer_test.go
When porting over the OP proposer code, the contract bindings were not set correctly. Use the correct contract bindings for the `ZKL2OutputOracle`.
```
t=2024-08-30T03:02:50+0000 lvl=error msg="failed to checkpoint block hash" err="method 'checkpointBlockHash' not found"
t=2024-08-30T03:02:50+0000 lvl=error msg="failed to request unrequested proofs" err="method 'checkpointBlockHash' not found"
```
Additionally, modify CI tests to run on merge to `main`.
> fix: contract bindings

- .github/workflows/compile.yaml
Compile the zkVM programs in CI.
> chore(ci): compile zkvm programs in ci

- book/node-setup.md
- scripts/prove/bin/cost_estimator.rs
Remove the dependency on the span batch server, as there aren't significant gains from optimizing the span batch boundaries when multiple span batches are included in the same proof.
Add documentation for L2 node setup.
> refactor: cost estimator + docs

- Cargo.lock
- Cargo.toml
- book/getting-started/l2-output-oracle.md
- book/getting-started/proposer.md
- programs/fault-proof/Cargo.toml
- programs/fault-proof/src/main.rs
- programs/range/Cargo.toml
- programs/range/src/main.rs
- rollup-configs/10.json
- rollup-configs/288882.json
- rust-toolchain
- scripts/prove/Cargo.toml
- scripts/prove/build.rs
- scripts/utils/bin/fetch_rollup_config.rs
- utils/client/Cargo.toml
- utils/client/src/boot.rs
- utils/client/src/driver.rs
- utils/client/src/l2_chain_provider.rs
- utils/client/src/oracle/mod.rs
- utils/client/src/precompiles/mod.rs
- utils/host/Cargo.toml
- utils/host/src/fetcher.rs
- utils/host/src/lib.rs
- utils/host/src/rollup_config.rs
- utils/host/src/witnessgen.rs
- Update to the latest Kona to incorporate better error handling and recent fixes.
- Set the `proposer` by default to the account set by `PRIVATE_KEY`.
- Add more clear documentation for the environment setup in `proposer.md`.
> feat: latest kona

- Cargo.lock
- Cargo.toml
- proposer/succinct/bin/server.rs
- scripts/utils/bin/fetch_and_save_proof.rs
> chore: `sp1-sdk` `rc3`

- proposer/op/proposer/config.go
- proposer/op/proposer/db/db.go
- proposer/op/proposer/driver.go
- proposer/op/proposer/flags/flags.go
- proposer/op/proposer/prove.go
- proposer/op/proposer/service.go
- proposer/succinct/bin/server.rs
- utils/host/src/fetcher.rs
- Remove unnecessary flags.
- Add error logging.
- Clear proofs in `WITNESSGEN` state at the start of the loop.
> chore(proposer): Remove unused flags + error logging

- proposer/op/proposer/db/db.go
Add a Mutex for the write client. Before, the `WriteClient` was not thread-safe, and would result in `database is locked` issues. Now, the `WriteClient` can be safely used.
> fix(proposer): SQLLite write mutex

- Cargo.lock
- configs/13269/rollup.json
- justfile
- scripts/utils/Cargo.toml
- scripts/utils/bin/update_vkeys.rs
- scripts/utils/bin/vkey.rs
- utils/host/src/fetcher.rs
Add a script to update the verification keys.
> feat(script): automatically update vkeys

- Cargo.lock
- proposer/op/proposer/driver.go
- proposer/op/proposer/prove.go
- proposer/op/proposer/rpc_types.go
- proposer/succinct/Cargo.toml
- proposer/succinct/bin/server.rs
- proposer/succinct/src/lib.rs
- scripts/utils/bin/update_vkeys.rs
- utils/host/Cargo.toml
- utils/host/src/lib.rs
Check the contract configuration for the aggregation + range verification keys as well as the rollup config hash.
> feat: validate contract config

- Cargo.lock
- Cargo.toml
- contracts/opsuccinctl2ooconfig.json
- proposer/db-utils/query_proofs.py
- proposer/op/proposer/driver.go
- scripts/prove/Cargo.toml
- scripts/prove/bin/agg.rs
- scripts/utils/bin/fetch_and_save_proof.rs
- utils/host/src/fetcher.rs
- Use `sp1-sdk` `3.0.0`.
- Refactor `agg` script.
- Clippy fixes.
> chore: cleanup

- docker-compose.yml
- proposer/op/go.mod
- proposer/op/op_proposer.sh
- proposer/op/proposer/driver.go
- proposer/op/proposer/metrics/metrics.go
- proposer/op/proposer/metrics/noop.go
- proposer/op/proposer/service.go
Add simple prometheus metrics that track the status of the `op-succinct-proposer`.
> feat(proposer): simple prometheus metrics

- utils/host/src/fetcher.rs
Simplify concurrent RPC requests from the fetcher.
> refactor: simplify fetcher

- Cargo.lock
- Cargo.toml
Change all patches to match the updated tags in the SP1 docs: https://docs.succinct.xyz/writing-programs/patched-crates.html
> chore: patches

- .github/workflows/integration-tests.yml
- .github/workflows/op_proposer.yaml
- Cargo.lock
- scripts/prove/Cargo.toml
- scripts/prove/bin/multi.rs
- scripts/utils/bin/cost_estimator.rs
Add CI testing to confirm that the `cost-estimator` script and the `multi` script work as expected.
> feat(ci): integration testing

- .github/actions/setup/action.yml
- .github/workflows/integration-tests.yml
> feat: update rust cache ci

- utils/host/src/fetcher.rs
This PR introduced a bug: https://github.com/succinctlabs/op-succinct/pull/223, where the URL passed to `kona`'s witness generation had a trailing slash. This PR removes the trailing slash and modifies the fetcher to store the `Url` type for better type-safety.
> fix(fetcher): RPC config

- book/quick-start/intro.md
- utils/host/src/fetcher.rs
> chore: remove todo's

- book/advanced/l2-output-oracle.md
- book/advanced/upgrade.md
- book/quick-start/upgrade-l2-output-oracle.md
- contracts/opsuccinctl2ooconfig.json
- contracts/script/OPSuccinctParameterUpdater.s.sol
- justfile
Add documentation for `upgrade-oracle` and `update-parameters`.
> docs: Upgrade documentation

- Cargo.lock
- Cargo.toml
Bump `kona` patch commit to include changes from https://github.com/anton-rs/kona/pull/846
> feat: kona fix

- book/SUMMARY.md
- book/advanced/upgrade.md
- book/quick-start/upgrade-l2-output-oracle.md
Upgrade documentation for `op-succinct` on a new release.
> docs: Upgrade

- Cargo.lock
- Cargo.toml
- configs/11155420/rollup.json
- contracts/opsuccinctl2ooconfig.json
- scripts/prove/bin/multi.rs
- scripts/utils/bin/cost_estimator.rs
- utils/host/src/block_range.rs
- Fix the SP1 version for the correct patch.
- Load env from path.
> chore: misc fixes

- Cargo.lock
- programs/fault-proof/Cargo.toml
- programs/fault-proof/src/main.rs
- scripts/prove/bin/single.rs
- scripts/utils/bin/cost_estimator.rs
- utils/host/src/fetcher.rs
- Increase `l1_head` by 20 blocks from the `optimism_safeHeadAtL1Block`.
- Add `tracing` logs to `fault_proof` program.
> feat: bump `l1_head` by 20 blocks

- contracts/opsuccinctl2ooconfig.json
- contracts/script/OPSuccinctParameterUpdater.s.sol
Update the `submissionInterval` in the `OPSuccinctParameterUpdater` script.
> feat(contracts): update submission interval in script

- .github/workflows/cost-estimator-manual.yml
- scripts/utils/bin/cost_estimator.rs
Add workflow which uses the cost estimator to execute 1000 blocks daily on OP Sepolia.
Add `default_range` parameter to `cost_estimator`.
> feat(ci): manual workflow

- book/advanced/kurtosis.md
- configs/2151908/rollup.json
- contracts/opsuccinctl2ooconfig.json
- op-network.yaml
- scripts/utils/bin/fetch_rollup_config.rs
- utils/host/src/block_range.rs
- utils/host/src/fetcher.rs
- Kurtosis devnet setup.
- Better error logging.
> feat: kurtosis

- Cargo.lock
- Cargo.toml
- configs/480/rollup.json
- contracts/opsuccinctl2ooconfig.json
- justfile
- proposer/succinct/Cargo.toml
- proposer/succinct/bin/server.rs
- scripts/prove/bin/agg.rs
- scripts/prove/bin/multi.rs
- scripts/prove/src/lib.rs
- scripts/utils/bin/cost_estimator.rs
- scripts/utils/bin/fetch_rollup_config.rs
- scripts/utils/bin/gen_sp1_test_artifacts.rs
- scripts/utils/bin/vkey.rs
- utils/build/src/lib.rs
- In mock mode, save the execution reports to `/execution-reports`.
> feat: mock proof from pv

- Cargo.lock
- Cargo.toml
- Bump to `rc.10`. 
- Fix the mock mode support.
> feat: `rc.10` bump

- proposer/op/Dockerfile.op_proposer
Useful utils for entrypoint and ops
> chore(proposer): add jq and nc to docker image

- book/advanced/proposer.md
- book/advanced/verify-binaries.md
- book/quick-start/full.md
- scripts/utils/bin/fetch_rollup_config.rs
This PR fixes broken links to the SP1 Docs.
> chore: fix broken links

- book/fault_proofs/fault_proof_architecture.md
This PR:
- Fixes mermaid diagram.
- Update immutable params.
- Make more comprehensive.
> docs: update `fault_proof_architecture.md`

- utils/host/src/fetcher.rs
Using the `finalized` block ensures that the L1 block used as the `l1Head` doesn't get re-orged.
> feat(fetcher): Use finalized block

- book/advanced/proposer.md
- proposer/succinct/bin/server.rs
- proposer/succinct/src/lib.rs
- scripts/utils/bin/fetch_rollup_config.rs
Allow customizing the aggregation proof mode in `server` with `AGG_PROOF_MODE`.
> feat(server): add proof mode

- book/SUMMARY.md
- book/fault_proofs/deploy.md
- book/fault_proofs/fault_proof_architecture.md
- book/fault_proofs/proposer.md
- book/fault_proofs/quick_start.md
- scripts/utils/Cargo.toml
- scripts/utils/bin/fetch_rollup_config_hash.rs
Updates the docs for zkfp to the most recent version of `OPSuccinctFaultDistpueGame`.
> docs: update docs for zkfp

- book/SUMMARY.md
- book/fault_proofs/gas_costs.md
Adds a doc for onchain gas costs of propose, challenge, prove, resolve.
> docs: add `gas_costs.md`

- scripts/prove/bin/multi.rs
- utils/build/src/lib.rs
- utils/client/src/client.rs
- utils/host/src/fetcher.rs
Only forget memory in zkVM mode.
> chore(program): memory allocation

- utils/host/src/fetcher.rs
- Add warning for inactive `safeDb`.
- Increase L1 head lookback.
> chore: fix

- Cargo.lock
- Cargo.toml
- book/advanced/proposer.md
- validity/Cargo.toml
- validity/bin/validity.rs
- validity/src/env.rs
- validity/src/lib.rs
- validity/src/signer.rs
Add support for signing with `Web3Signer`.
> feat: Add `Web3Signer` support

- utils/host/src/block_range.rs
- utils/host/src/fetcher.rs
Improve on naive search with binary search for L1 block.
> feat(proposer): search for L1 block

- Cargo.lock
- Cargo.toml
- utils/host/Cargo.toml
- utils/host/src/fetcher.rs
- validity/Cargo.toml
- validity/src/prom.rs
- validity/src/proof_requester.rs
- validity/src/proposer.rs
Adds more metrics: ProofRequestRetryCount, ProofRequestTimeoutErrorCount, RetryErrorCount, WitnessgenErrorCount, ExecutionErrorCount, RangeProofRequestErrorCount, AggProofRequestErrorCount, and RelayAggProofErrorCount.
> feat(validity): add more metrics

- Cargo.lock
- Cargo.toml
- book/fault_proofs/challenger.md
- book/fault_proofs/deploy.md
- book/fault_proofs/docker.md
- book/fault_proofs/proposer.md
- fault-proof/Cargo.toml
- fault-proof/bin/challenger.rs
- fault-proof/bin/proposer.rs
- fault-proof/docker-compose.yml
- fault-proof/grafana/dashboards/dashboard.json
- fault-proof/grafana/provisioning/dashboards/dashboard.yml
- fault-proof/grafana/provisioning/datasources/datasource.yml
- fault-proof/prometheus/prometheus.yml
- fault-proof/src/config.rs
- fault-proof/src/lib.rs
- fault-proof/src/prometheus.rs
- fault-proof/src/proposer.rs
- utils/host/Cargo.toml
- utils/host/src/lib.rs
- utils/host/src/metrics.rs
- validity/Cargo.toml
- validity/bin/validity.rs
- validity/src/prom.rs
- validity/src/proof_requester.rs
- validity/src/proposer.rs
Adds proposer, challenger metrics for OP Succinct Lite.
> feat: add fp metrics

- book/SUMMARY.md
- book/fault_proofs/upgrade.md
- contracts/script/fp/UpgradeOPSuccinctFDG.s.sol
- contracts/src/fp/OPSuccinctFaultDisputeGame.sol
- fault-proof/justfile
Adds just command to upgrade OPSuccinctFaultDisputeGame contract.
Has a `DRY_RUN` environment variable to allow simulation before actual upgrade.
> feat: add contract upgrade script for fp

- book/fault_proofs/quick_start.md
- book/introduction.md
- Fixed an incorrect link in the ZK fault proof section
- Fixed a typo
> docs: update

- book/SUMMARY.md
- book/fault_proofs/docker.md
- book/fault_proofs/experimental/celestia.md
- book/fault_proofs/experimental/experimental.md
- fault-proof/Dockerfile.proposer.celestia
- fault-proof/bin/proposer.rs
- fault-proof/docker-compose-celestia.yml
- fault-proof/src/proposer.rs
- fault-proof/tests/integration.rs
Adds Celestia DA support for op-succinct-lite as well.
Tested e2e with fast finality mode: [Factory Proxy](https://sepolia.etherscan.io/address/0x2b69d2bC1C368994E1E10F9aa6eD25a7bDafd2E6).
> feat: support Celestia for op-succinct lite

- book/fault_proofs/deploy.md
- book/validity/proposer-lifecycle.md
- book/validity/proposer.md
- programs/aggregation/src/main.rs
- scripts/prove/bin/agg.rs
- scripts/prove/bin/multi.rs
- scripts/prove/tests/common/mod.rs
- scripts/utils/bin/block_data.rs
- scripts/utils/bin/config.rs
- scripts/utils/bin/cost_estimator.rs
- scripts/utils/bin/fetch_and_save_proof.rs
- scripts/utils/bin/fetch_rollup_config.rs
- scripts/utils/bin/gen_sp1_test_artifacts.rs
- utils/host/src/block_range.rs
- utils/host/src/fetcher.rs
- utils/host/src/hosts/celestia.rs
- validity/src/db/types.rs
- validity/src/signer.rs
Fixes broken link. Also updated some links for better developer experience.
> docs: fix broken link and update link

- book/SUMMARY.md
- book/advanced/cost-estimator.md
Adds docs on how to run the cost estimator.
> docs: add cost estimator docs

- .github/workflows/docker-build-lite.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/elf.yml
so expensive ci jobs actually finish
> feat: no more spot

- book/fault_proofs/proposer.md
- fault-proof/src/config.rs
- fault-proof/src/prometheus.rs
- fault-proof/src/proposer.rs
- fault-proof/tests/common/process.rs
Improves fast finality mode in op succinct lite proposer.
> feat: prove task improvements

- fault-proof/src/lib.rs
- fault-proof/src/prometheus.rs
- fault-proof/src/proposer.rs
- scripts/prove/bin/agg.rs
- scripts/prove/src/lib.rs
- scripts/utils/bin/cost_estimator.rs
- validity/src/proof_requester.rs
Adding more game proving stats for op-succinct-lite proposer to track performance.
Also improved logging for better visibility and debugging.
> feat: add cycles + prover gas metrics

- validity/src/proposer.rs
> chore: range proof insertion log to debug

- README.md
- book/SUMMARY.md
- book/advanced/node-setup.md
- book/advanced/verify-binaries.md
- book/architecture.md
- book/fault_proofs/contracts.md
- book/repository-structure.md
- book/validity/contracts/intro.md
- book/validity/contracts/toggle-optimistic.md
- book/validity/contracts/update-parameters.md
- Add warning about latency issues when L2 nodes and proposer are not in the same region/network
- Miscellaneous cleanup and improvements
> docs: L2 node latency + cleanup

- Cargo.lock
- Cargo.toml
> chore: bump hana to v1.0.0

- book/fault_proofs/experimental/celestia.md
- book/fault_proofs/experimental/eigenda.md
- book/validity/experimental/celestia.md
- book/validity/experimental/eigenda.md
Improving docs to make altda deployments more clear.
> docs: make altda deployments more clear

- .github/workflows/cycle-count-diff-celestia.yml
- Cargo.lock
- scripts/prove/Cargo.toml
- scripts/prove/bin/multi.rs
- scripts/prove/src/lib.rs
- scripts/prove/tests/cycle_count_diff.rs
- scripts/prove/tests/multi.rs
- scripts/utils/bin/cost_estimator.rs
- scripts/utils/bin/gen_sp1_test_artifacts.rs
- utils/host/src/block_range.rs
Adds cycle count diff ci for celestia range elf to prevent proving cost blowing up.
Tested in #574.
> ci: add cycle count diff ci for celestia range elf
